/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lab;

import com.lab.queue.data.QueueNode;
import com.lab.queue.structure.Queue;
import com.lab.stack.data.StackNode;
import com.lab.stack.structure.Stack;

public class App {
    public static void main(String[] args) {
        System.out.println("############## Stack ##############");

        Stack stack = new Stack();

        stack.push(new StackNode(1));
        stack.push(new StackNode(2));

        System.out.println(stack.peek());
        System.out.println(stack.pop());

        System.out.println(stack);

//        System.out.println("############## Queue ##############");
//
//
            Queue queue =new Queue();
        System.out.println(queue.enqueue(new QueueNode(1)));
        System.out.println(queue.enqueue(new QueueNode(2)));

        System.out.println(queue.peek());
//            queue.enqueue(new QueueNode(2));
//            queue.enqueue(new QueueNode(3));
//            queue.enqueue(new QueueNode(4));
//
////            System.out.println(queue.dequeue());
//            queue.dequeue();
//
//            System.out.println(queue);






    }
}
