/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lab;

import com.lab.queue.data.QueueNode;
import com.lab.queue.structure.Queue;
import com.lab.stack.data.StackNode;
import com.lab.stack.structure.Stack;

public class App {
    public static void main(String[] args) {
        System.out.println("############## Stack ##############");

        Stack stack = new Stack();

        stack.push(new StackNode(1));
        stack.push(new StackNode(2));

        System.out.println(stack.peek());
        System.out.println(stack.pop());

        System.out.println(stack);

        System.out.println("############## Queue ##############");
//
//
            Queue<Integer> queue =new Queue<>();

        System.out.println(queue.enqueue(5));
            queue.enqueue(3);
            queue.enqueue(1);

        System.out.println(queue.peek());
        System.out.println("Deleted data => "+queue.dequeue());

        System.out.println(queue.peek());

        System.out.println(queue);

    }
}
