/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quickSort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
//    @Test void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }

    @Test void quickSortTest(){
        int[] arr = {8,4,23,42,16,15};
        App.quickSort(arr,0, arr.length-1);
        int[] expected = {4, 8, 15, 16, 23, 42};

        assertArrayEquals(expected,arr);


        int[] arr2 = new int[]{};
        App.quickSort(arr2,0, arr2.length-1);
        int[] expected2 = {};

        assertArrayEquals(expected2,arr2);
    }
}
