/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergeSort;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {

        ArrayList<Integer> arrayList = new ArrayList<>();
        arrayList.add(4);
        arrayList.add(23);
        arrayList.add(42);
        arrayList.add(16);
        arrayList.add(15);

        System.out.println(mergeSort(arrayList));


    }

    public static ArrayList<Integer> mergeSort(ArrayList<Integer> arr){
        int n = arr.size();
        if(n>1) {
            int mid = n / 2;
            ArrayList<Integer> left = new ArrayList<>();
            for (int i = 0; i < mid; i++) {
                left.add(arr.get(i));
            }

            ArrayList<Integer> right = new ArrayList<>();
            for (int i = mid; i < arr.size(); i++) {
                right.add(arr.get(i));
            }

            mergeSort(left);
            mergeSort(right);
            Merge(left, right, arr);
        }
        System.out.println("Arr => " + arr);
        return arr;
    }


    public static ArrayList<Integer> Merge(ArrayList<Integer> left , ArrayList<Integer> right , ArrayList<Integer> arr) {
        int i = 0 ;
        int j = 0 ;
        int k = 0 ;

        while (i<left.size() && j < right.size()){
            if(left.get(i) < right.get(j))
            {
                arr.set(k , left.get(i));
                i++;
            }
            else
            {
                arr.set(k , right.get(j));
                j++;
            }
            k++;
        }
        // Collect remaining elements
        while(i < left.size())
        {
            arr.set(k , left.get(i));
            i++;
            k++;
        }
        while(j < right.size())
        {
            arr.set(k , right.get(j));
            j++;
            k++;
        }
        return arr ;
    }
}
