/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import java.util.ArrayList;

public class App {


    public static void main(String[] args) {

        Graph graph = new Graph();

        graph.addNode("a");
        graph.addNode("b");
        graph.addNode("c");
        graph.addNode("d");
        graph.addNode("e");
        graph.addNode("f");
        graph.addNode("g");
        graph.addNode("h");

        graph.addEdges("a","b");
        graph.addEdges("b","c");
        graph.addEdges("c","g");
        graph.addEdges("a","d");

        graph.addEdges("b","d");

        graph.addEdges("d","e");
        graph.addEdges("d","h");
        graph.addEdges("d","f");
        graph.addEdges("f","h");


        System.out.println(graph.dfs(graph,"a"));


    }

    public static String businessTripCost(Graph graph , ArrayList<String> cities){

       int cost = 0;
       for(int i = 0; i<cities.size() - 1 ; i++){
           cost += graph.getWeight(cities.get(i),cities.get(i+1));
       }
       if(cost == 0 ){
           return null;
       }
       return cost +"$";
    }

    public static void matrix(String[] nodes, String[][] array, Graph graph){

        int index = 0;
        for (String[] strArr: array
        ) {
            for(int i = 0 ; i< strArr.length;i++){
                if(strArr[i].equals("t")){
                    graph.addEdges(nodes[index],nodes[i]);
                }
            }
            index++;
        }

    }
}
