/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import java.util.Set;

public class App {


    public static void main(String[] args) {

        Graph graph = new Graph();

        graph.addNode("A");
        graph.addNode("B");
        graph.addNode("C");

        graph.addEdges("A","B");
        graph.addEdges("B","C");
        graph.addEdges("A","C");

        System.out.println(graph.getVertices());
        System.out.println(graph.dfs(graph,"A"));
        System.out.println(graph.bfs(graph,"A"));
//        System.out.println(graph.size(graph));
    }
}
