/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {


    public static void main(String[] args) {

        Graph graph = new Graph();

        graph.addNode("A");
        graph.addNode("B");
        graph.addNode("C");

        graph.addEdges("A","C");

        graph.addEdges("B","A",25);
        graph.addEdges("C","B",30);

        System.out.println(graph.getNode());
        System.out.println("");

        System.out.println(graph.getNeighbors("A"));
        System.out.println(graph.getNeighbors("B"));
        System.out.println(graph.getNeighbors("C"));
        System.out.println("");

        System.out.println(graph.size());


//        System.out.println(graph.size(graph));
    }
}
