/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergeSort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {

        int[] arr1 = {20,18,12,8,5,-2};
        int[] arr2 = {5,12,7,5,5,7};
        int[] arr3 = {2,3,5,7,13,11};


        int[] expected1 = {-2,5,8,12,18,20};
        int[] expected2 = {5,5,5,7,7,12};
        int[] expected3 = {2,3,5,7,11,13};


       App.mergeSort(arr1,0,arr1.length);
       assertArrayEquals(expected1,arr1);

        App.mergeSort(arr2,0,arr2.length);
        assertArrayEquals(expected2,arr2);

        App.mergeSort(arr3,0,arr3.length);
        assertArrayEquals(expected3,arr3);


    }
}
