/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergeSort;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {

        ArrayList<Integer> arrayList = new ArrayList<>();
        arrayList.add(8);
        arrayList.add(4);
        arrayList.add(23);
        arrayList.add(42);
        arrayList.add(16);
        arrayList.add(15);
        ArrayList<Integer> arr1 = App.mergeSort(arrayList);
        ArrayList<Integer> arr2 = new ArrayList<>();
        arr2.add(4);
        arr2.add(8);
        arr2.add(15);
        arr2.add(16);
        arr2.add(23);
        arr2.add(42);
        assertEquals(arr1 , arr2);


    }
}
