/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

import hashTable.structure.HashMap;

public class App {


    public static void main(String[] args) {

        HashMap<String,String>hashMap = new HashMap<>();

        hashMap.set("JAVA", "JAVA");
        hashMap.set("Amman", "Amman");
        hashMap.set("Jordan", "Jordan");
        hashMap.set("J", "J");
        hashMap.set("Bob", "Bab");
        hashMap.set("Carl", "Carl");

        System.out.println(hashMap.contain("J"));

        System.out.println(hashMap.get("Bob"));
        System.out.println(hashMap.getSize());
        
        System.out.println(repeatedWord("It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only..."));
        System.out.println(repeatedWord("Once upon a time, there was a brave princess who..."));


    }


    public static String repeatedWord (String str){
        String[] strArr = str.split(" ");
        HashMap<String,String> hashMap = new HashMap<>();

        for(String word:
                strArr){
            word = word.toLowerCase().replaceAll(",","");
            if(hashMap.contain(word)){
                return word;
            }else {
                hashMap.set(word,word);
            }
        }
        return "There are no duplicate";
    }
}
