/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

public class App {

    public static void main(String[] args) {

        int[] arr = {20,18,12,8,5,-2};
        int[] newArr = InsertionSort(arr);

        for (int i = 0; i<newArr.length ;i++ ){
            System.out.println(newArr[i]);
        }

    }

    public static int[] InsertionSort(int[] arr){
        for (int i = 1 ; i < arr.length;i++){
            int j = i-1;
            int temp = arr[i];

            while (j >= 0 && temp <arr[j]){
                arr[j+1] = arr[j];
                j = j-1;
                arr[j+1] = temp;
            }
        }
        return arr;
    }
}
