/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import trees.Data.BinaryNode;
import trees.structure.BinarySearchTree;
import trees.structure.BinaryTree;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    BinarySearchTree<Integer> binarySearchTree;

    @BeforeEach
    void setUp(){
             binarySearchTree = new BinarySearchTree<>();
    }

    @Test void addTest(){
        binarySearchTree.add(5);
        binarySearchTree.add(2);
        binarySearchTree.add(8);
        binarySearchTree.add(1);
        binarySearchTree.add(3);
        binarySearchTree.add(7);
        binarySearchTree.add(9);
        assertEquals(7,binarySearchTree.getSize());
    }

    @Test void containsTest(){
        binarySearchTree.add(5);
        binarySearchTree.add(2);
        binarySearchTree.add(8);
        binarySearchTree.add(1);
        binarySearchTree.add(3);
        binarySearchTree.add(7);
        binarySearchTree.add(9);

        assertTrue(binarySearchTree.contains(9));
        assertFalse(binarySearchTree.contains(11));
    }
}
