/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.challeng;

import com.challeng.Quere.data.Animal;
import com.challeng.Quere.structure.AnimalShelter;
import org.checkerframework.checker.units.qual.A;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    AnimalShelter animalShelter;

    @BeforeEach
    void setUp(){
        animalShelter = new AnimalShelter();
    }

    @Test void enQueueTest() {

        boolean actual1 = animalShelter.enQueue(new Animal("mary","cat"));
        assertTrue(actual1);

        boolean actual2 = animalShelter.enQueue(new Animal("lion","lion"));
        assertFalse(actual2);
    }

    @Test void deQueueTest1(){
        animalShelter.enQueue(new Animal("pop","dog"));
        animalShelter.enQueue(new Animal("12","dog"));
        animalShelter.enQueue(new Animal("mari","cat"));
        animalShelter.enQueue(new Animal("meme","cat"));
        animalShelter.enQueue(new Animal("1","dog"));

        Animal expected1 = new Animal("pop","dog");

        Animal actual1 = animalShelter.deQueue("");
        assertEquals(expected1.toString(),actual1.toString());

        Animal expected2 = new Animal("mari","cat");
        Animal actual2 = animalShelter.deQueue("cat");
        assertEquals(expected2.toString(),actual2.toString());

        Animal expected3 = new Animal("12","dog");
        Animal actual3 = animalShelter.deQueue("dog");
        assertEquals(expected3.toString(),actual3.toString());
    }
}
