/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BreadthFirst;

import BreadthFirst.TreeStructure.Tree;

public class App {


    public static void main(String[] args) {
        Tree<Integer> tree = new Tree<>();

        tree.add(15);
        tree.add(13);
        tree.add(17);
        tree.add(4);
        tree.add(12);
        tree.add(16);
        tree.add(18);
        tree.add(23);


        tree.traverse(Tree.TraversalOrder.BreadthFirst);


    }
}
