/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzBuzz;

import fizzBuzz.Structure.BinaryTree;

public class App {
    public static void main(String[] args) {

        BinaryTree<Integer> tree = new BinaryTree<>();

        tree.add(10);
        tree.add(5);
        tree.add(15);
        tree.add(2);
        tree.add(9);
        tree.add(11);
        tree.add(21);

        tree.traverse(BinaryTree.TraversalOrder.PREORDER);

        tree.fizzbuzz();



    }
}
