/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BreadthFirst;

import BreadthFirst.TreeStructure.Tree;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void BreadthFirstTest() {
        Tree<Integer> tree = new Tree<>();

        tree.add(15);
        tree.add(13);
        tree.add(17);
        tree.add(4);
        tree.add(12);
        tree.add(16);
        tree.add(18);
        tree.add(23);


        String result = tree.BreadthFirst();

        assertEquals("15 13 17 4 16 18 12 23 ",result);

    }
}
