/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.linkedlist;

public class App {


    public static void main(String[] args) {
//        LinkedList<Integer> newList = new LinkedList();
        LinkedList<Integer> newList = new LinkedList();
        newList.insert(1);
        newList.insert(3);
        newList.insert(4);
        newList.insert(8);

        newList.append(7);

        newList.insertAfter(8,5);
//        newList.insertBefore(4,5);
//        System.out.println(newList.includes(-3));
        System.out.println(newList.toString());

        newList.kth(3);
        newList.kth(0);
        newList.kth(-5);
        newList.kth(8);
    }

}
