/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.linkedlist;

public class App {


    public static void main(String[] args) {

        LinkedList<Integer> list1 = new LinkedList();
        list1.insert(1);
        list1.insert(3);
        list1.insert(4);
        list1.insert(8);

        LinkedList<Integer> list2 = new LinkedList();
        list2.insert(2);
        list2.insert(7);
        list2.insert(9);
        list2.insert(5);

        System.out.println(list1);
        LinkedList<Integer> reversList = new LinkedList<>();

        list1.reverse(list1);
        System.out.println(list1);


//        newList.insertAfter(8,5);
//        System.out.println(newList.includes(-3));
//        System.out.println(list1.kth(3));
//        newList1.kth(0);
//        newList1.kth(-5);
//        newList1.kth(8);

//        System.out.println(list1.toString());
//        System.out.println(list2.toString());
//        LinkedList<Integer> mergeList = new LinkedList<>();
//
//        mergeList.zip(list1,list2);
//        System.out.println(mergeList);





    }
    public static LinkedList<Integer> reverseLinkelist(LinkedList<Integer> list){
        Node p = null ;
        Node n = list.head;
        Node c = list.head ;

        while (c !=null){
            n = c.next;
            c.next =p;
            p = c;
            c = n;
        }
        LinkedList<Integer> rev = new LinkedList<>();
        return rev;
    }

}
