/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {
    Graph graph;
    @BeforeEach
    void setUp(){
        graph = new Graph();
    }

    @Test void graphAddNodeTest(){
        graph.addNode("A");
        graph.addNode("B");

        String actual = graph.getNode();

        assertEquals("Vertex{data='A', weight=0}[]Vertex{data='B', weight=0}[]",actual);
    }

    @Test void graphEdgeTest(){
        graph.addNode("A");
        graph.addNode("B");

        graph.addEdges("A","B");
        String actual = graph.getNode();

        assertEquals("Vertex{data='A', weight=0}[Vertex{data='B', weight=0}]Vertex{data='B', weight=0}[Vertex{data='B', weight=0}]",actual);
    }

    @Test void neighborsTest(){
        graph.addNode("A");
        graph.addNode("B");

        graph.addEdges("A","B",20);

        assertEquals("[Vertex{data='B', weight=20}]",graph.getNeighbors("A").toString());

    }
    @Test void getSizeTest(){
        graph.addNode("A");
        graph.addNode("B");

        int size = graph.size();

        assertEquals(2,size);
    }
}
