/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {
    Graph graph;
    @BeforeEach
    void setUp(){
        graph = new Graph();
    }

    @Test void graphAddNodeTest(){
        graph.addNode("A");
        graph.addNode("B");

        String actual = graph.getVertices();

        assertEquals("Vertex{data='A'}[]Vertex{data='B'}[]",actual);
    }

    @Test void graphEdgeTest(){
        graph.addNode("A");
        graph.addNode("B");

        graph.addEdges("A","B");
        String actual = graph.getVertices();

        assertEquals("Vertex{data='A'}[Vertex{data='B'}]Vertex{data='B'}[Vertex{data='B'}]",actual);
    }

    @Test void neighborsTest(){
        graph.addNode("A");
        graph.addNode("B");

        graph.addEdges("A","B");
        String actual = String.valueOf(graph.bfs(graph,"A"));

        assertEquals("[A, B]",actual);


    }
}
