/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.challeng;

import com.challeng.Quere.data.Animal;
import com.challeng.Quere.structure.AnimalShelter;

public class App {


    public static void main(String[] args) {
        AnimalShelter animalShelter = new AnimalShelter();

        animalShelter.enQueue(new Animal("pop","dog"));
        animalShelter.enQueue(new Animal("12","dog"));
        animalShelter.enQueue(new Animal("mari","cat"));
        animalShelter.enQueue(new Animal("meme","cat"));
        animalShelter.enQueue(new Animal("1","dog"));


        try {
            System.out.println(animalShelter.deQueue(""));
            System.out.println(animalShelter.deQueue("cat"));
            System.out.println(animalShelter.deQueue("dog"));
        }catch (Exception e){
            System.err.println(e.getMessage());
        }

    }
}
